on:
  workflow_call:
    inputs:
      print-inputs:
        description: print input variables
        required: false
        default: false
        type: boolean
      environment:
        description: deploy to this environment
        required: true
        type: string
      cluster:
        description: cluster to deploy to
        required: true
        type: string
- if: inputs.print-inputs
  run: |
    {
      echo "### :rocket: Workflow inputs"
      echo "| Arg                 | Value |"
      echo "| ------------------- | ----- |"
      echo "| Print inputs        | ${{ inputs.print-inputs }} |"
      echo "| Environment         | ${{ inputs.environment }} |"
      echo "| Cluster             | ${{ inputs.cluster }} |"
    } >> $GITHUB_STEP_SUMMARY        
        
